name: PHP Tests 

on:
  push:
    branches: [ "master", "develop", "github-actions-test" ]
  pull_request:
    branches: [ "master", "develop", "github-actions-test" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP 8.4
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.4.2
        extensions: imagick, gd
        ini-values: memory_limit=-1
        tools: composer:v2
        coverage: none

    - name: Validate composer.json and composer.lock
      run: composer validate
    
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Imagick and GD 
      run: |
          sudo apt-get install -y ghostscript

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Verify Formatting
      run: PHP_CS_FIXER_IGNORE_ENV=true ./vendor/bin/php-cs-fixer check

    - name: Verify phpstan 
      run: composer analyze 

    - name: Configure Imagick Permissions 
      run: sudo cp -f ./.github/github-actions-imagick-config.xml /etc/ImageMagick-6/policy.xml

    - name: Run test suite
      run: composer test

    - name: Show PHPUnit logs on failure
      if: failure()
      run: |
        echo "Showing PHPUnit logs..."
        cat phpunit-junit.xml || echo "No JUnit logs found"
        cat phpunit-testdox.txt || echo "No TestDox logs found"
