name: PHP 8.1 Workflow

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  call-php-base:
    uses: ./.github/workflows/php.yml
    with:
      php-version: '8.1'
